server:
  port: 8082

spring:
  profiles:
    active: dev

#单数据源mybatis
# 该配置节点为独立的节点，容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.emotte.springbootdemo.mybatis.mapper  # 注意：对应实体类的路径

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

my:
  name: boot
  age: 18
  max: ${random.int(10)}

#server:
#  port: 443
#  ssl:
#    key-store: keystore.p12
#    key-store-password: springboot
#    keyStoreType: PKCS12
#    keyAlias: tomcat


